ALTER TABLE "GalleryCard" ADD COLUMN "category" TEXT NOT NULL DEFAULT 'car';
ALTER TABLE "GalleryCard" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "GalleryCard" ADD COLUMN "vehicleBrand" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GalleryCard" ADD COLUMN "vehicleModel" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GalleryCard" ADD COLUMN "wheelType" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GalleryCard" ADD COLUMN "wheelSpecification" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GalleryCard" ADD COLUMN "flickrAlbumId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GalleryCard" ADD COLUMN "flickrCoverUrl" TEXT NOT NULL DEFAULT '';
